[package]

name = "hello"
version = "0.0.1"
authors = ["Shipeng Feng <fsp261@gmail.com>"]

[dependencies.pencil]
path = "../.."
default_features = false

[dependencies]
typemap = "*"
log = "*"
env_logger = "*"
